name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "theme": {
                "color": {
                  "background": "#2E2910",
                  "text": "#EBE3A7",
                  "level0": "#2C5745",
                  "level1": "#4B6B40",
                  "level2": "#768630",
                  "level3": "#B0AA14",
                  "level4": "#EB7D00"
                }
              }
            }
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contribution graph" || exit 0
          git push
